McShelby/hugo-theme-relearn

exampleSite/content/basics/configuration/_index.en.md, exampleSite/content/basics/customization/_index.en.md, exampleSite/content/basics/installation/_index.en.md, exampleSite/content/cont/syntaxhighlight.en.md, exampleSite/layouts/partials/logo.html, layouts/partials/header.html, layouts/partials/logo.html, layouts/partials/menu.html, netlify.toml, static/css/theme-blue.css, static/css/theme-green.css, static/css/theme-red.css, static/css/theme-relearn.css, static/css/theme.css
Some fixes and clean-ups:
* copy-to-clipboard icon looked stretched
* Home link didn't work correctly when base URL has some path
* Typo in custom theme's variable: --MENU-HOME-LINK-HOVER**ED**-color
* Fixed some exampleSite typos and other minor clean-ups
=> Improve copy-to-clipboard, fix home link, clean up exampleSite

layouts/index.json, layouts/partials/search.html, static/js/search.js
The search currently doesn't work properly when using `relativeURLs` and serving the site in some subpath, as it will always try to load the search index from `/index.json`, instead of being relative to the current page.
=> Fix search with relativeURLs

exampleSite/content/basics/_index.en.md, exampleSite/content/cont/_index.en.md, exampleSite/content/shortcodes/_index.en.md, exampleSite/layouts/partials/menu-pre.html, layouts/partials/menu-post.html, layouts/partials/menu-pre.html, layouts/partials/menu.html
This PR adds partial templates `menu-pre.html` and `menu-post.html` to allow easier customisation of the menu look & feel. I have a use-case where I want to add a badge to each menu entry based on a property in that page front matter. That's already possible with the `pre` field but that leads to too much duplication as I'd have to write the full HTML for the badge in every page. I'd like to just have a page property like `status: ok` or `status: failed` and then have the respective HTML for the badge in  `menu-pre.html`.
=> Add menu-pre and menu-post templates

exampleSite/content/basics/configuration/_index.en.md, layouts/index.json
`index.json` is currently overly escaped, which makes strange characters appear in the search context preview.
This also removes hidden pages from the search.
=> Fix index.json encoding

layouts/partials/favicon.html
If `favicon.ico` or `logo.ico` exists, `/images/favicon.icon`  or `/images/logo.icon`  should be `/images/favicon.ico`  or `/images/logo.ico`.
=> Fix icon filename extension

i18n/en.toml, i18n/zh-cn.toml, layouts/index.html
Although the toggle only appears when the page is too thin to show both navigation and content, adding i18n support do no harm.
=> add i18n support for navigation toggle

static/css/theme.css
It is usually recommended to add  `font-display: swap;` to `@font-face` definitions.
This will speed up font loading for the user mainly on initial page load. Without `font-display: swap;` the users sees no fonts before the web font is loaded. With `font-display: swap;` a fallback font is used (for that blink of a second).
See https://fontsplugin.com/google-fonts-font-display-swap/
=> theme: improve font loading

exampleSite/config.toml
This fixes the edit url button on your example site.
=> exampleSite: fix editURL

layouts/partials/footer.html
The HTML closing tags for #chatper and #body-inner in footer.html are in wrong order. The #chapter block should enclose the #body-inner block.
=> Fix HTML closing tags in footer.html

i18n/ja.toml
Improve Japanese translation of some default titles for `notice` shortcode.
Current translation looks unnatural for native Japanese speaker.
=> Improve Japanese translation of default titles

exampleSite/content/shortcodes/mermaid.en.md, layouts/_default/_markup/render-codeblock-mermaid.html
This PR improves the `mermaid` render code block so that it accepts the `align` parameter for content aligment.
=> Mermaid diagrams: allow passing of parameters with codefence syntax

exampleSite/content/basics/customization/_index.en.md, layouts/partials/favicon.html
=> favicon: add light & dark option for OS's prefered color scheme

static/js/theme.js
Mermaid diagrams can start with yaml front matter, e.g.
```
---
title: Example Diagram
---
graph LR
A --> B
```
Relearn injects an init directive
`%%{init: {"theme":"default"}}%%` at the top of a mermaid block to support theming the mermaid diagram. However this will cause a syntax parser error in mermaid if the init directive comes before the yaml front matter.
Valid:
```
%%{init: {"theme":"default"}}%%
graph LR
A --> B
```
Invalid:
```
%%{init: {"theme":"default"}}%%
---
title: Example
---
graph LR
A --> B
```
To support yaml front matter, we detect if front matter is used, and inject the init directive after the front matter.
```
---
title: Example
---
%%{init: {"theme":"default"}}%%
graph LR
A --> B
```
=> Support yaml front matter in mermaid blocks

exampleSite/content/shortcodes/icon.en.md
To use icons via HTML elements directly, unsafe markup must be allowed.
The note is copied from the shortcode "buttons", so it might be better to move the description to a central place and reference it here.
The additional changes were recommended by Grammarly.
=> add note for HTML markup

static/js/theme.js
There is a spelling mistake in the Swagger Docs.
`Exapnd` to `Expand`
=> Fix spelling in Swagger Docs

layouts/partials/topbar/button/edit.html
The rationale is that sometimes a page could be edited using a different URL than the declared site schema.
With this PR, a page can override the global URL schema giving its own already complete URL.
It also allows not to set the site editURL param, but only set it in a few pages that can be edited.
The docs have to be changed, but I wanted to check whether the idea is worth it or not before doing it.
=> topbar: edit button supports page editURL param before site one

layouts/partials/bodys/taxonomy.html, layouts/partials/bodys/term.html
The taxonomy and terms pages display a blank page below the title.
To be sure, I've created a fresh new site with the [Getting Start tutorial](https://mcshelby.github.io/hugo-theme-relearn/introduction/quickstart/index.html#create-content) and I got the same blank content.
Removing the `.RenderString` in both `layouts/partials/bodys/taxonomy.html` and `layouts/partials/bodys/term.html` templates fix the problem in my configuration.
=> Removing RenderString fix taxonomy and term render

layouts/partials/versioning-warning.html
This commit adds a unique class to the versioning warning partial.
Yes it can be modified as a partial, but this allows it to be styled using css as well.
=> versioning: add unique class to warning

i18n/es.toml
"Capitulo" should be (here) "Capítulo" (otherwise it's a verb).
=> Fixed spelling mistake in es.toml

docs/content/configuration/sidebar/menus/_index.en.md, docs/content/development/contributing/_index.en.md
- correct typo in configuration/sidebar/menus
- correct typo in development/contributing
=> docs: fix two small typos
